site_name: Documentação - SIGEsporte
site_url: https://fga0138-mds-ajax.github.io/2026.1-T01-Dijkstra/

nav:
  - Instruções mkdocs: "index.md"
  - Atas de Reunião:
    - Ata 20/04 - Elaboração do Documento de Visão: "atas-reuniao/a-ata-reuniao-20-04.md"
    - Ata 06/05 - Elaboração do Documento de Arquitetura: "atas-reuniao/ata-reuniao-06-05.md"
  - Documento de Visão:
    - Documento de Visão: "documentos/Documento de Visao/ESCOPO_VISAO_DO_PRODUTO.md"    
  - Documento de Arquitetura:
    - Documento de Arquitetura: "documentos/Documento de Arquitetura/Documento de arquitetura.md"
  - Diagramas:
    - Diagrama de Classes: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE CLASSES .png"
    - Diagrama de Entidade-Relacionamento: "Imagens/Diagramas/SIGESPORTE - MODELAGEM DE DADOS.png"
    - Diagrama de Arquitetura: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE ARQUITETURA.png"
    - Caso de Uso - Criação de Evento: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE SEQUENCIA - CRIACAO DE EVENTO.png"
    - Caso de Uso - Inscrição em Evento: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE SEQUENCIA - INSCRIÇÃO EM EVENTO.png"
    - Diagrama MVC: "Imagens/Diagramas/DIAGRAMA MVC.png"
    - Diagrama de Deploy: "Imagens/Diagramas/DIAGRAMA DE DEPLOY.png"
  - Protótipos:
    - Protótipo de Baixa Fidelidade: prototipos/baixa_fidelidade/prototipo_baixa_fidelidade.md


theme:
  name: material