site_name: Documentação - SIGEsporte
site_url: https://fga0138-mds-ajax.github.io/2026.1-T01-Dijkstra/

nav:
  - Instruções mkdocs: "index.md"
  - Atas de Reunião:
    - Ata 20/04 - Elaboração do Documento de Visão: "atas-reuniao/a-ata-reuniao-20-04.md"
    - Ata 06/05 - Elaboração do Documento de Arquitetura: "atas-reuniao/ata-reuniao-06-05.md"
  - Documento de Visão:
    - Documento de Visão: "documentos/Documento de Visao/ESCOPO_VISAO_DO_PRODUTO.md"    
  - Documento de Arquitetura:
    - Documento de Arquitetura: "documentos/Documento de Arquitetura/Documento de arquitetura.md"
  - Diagramas:
    - Diagrama de Classes: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE CLASSES .png"
    - Diagrama de Entidade-Relacionamento: "Imagens/Diagramas/SIGESPORTE - MODELAGEM DE DADOS.png"
    - Diagrama de Arquitetura: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE ARQUITETURA.png"
    - Caso de Uso - Criação de Evento: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE SEQUENCIA - CRIACAO DE EVENTO.png"
    - Caso de Uso - Inscrição em Evento: "Imagens/Diagramas/SIGESPORTE - DIAGRAMA DE SEQUENCIA - INSCRIÇÃO EM EVENTO.png"
    - Diagrama MVC: "Imagens/Diagramas/DIAGRAMA MVC.png"
    - Diagrama de Deploy: "Imagens/Diagramas/DIAGRAMA DE DEPLOY.png"
  - Protótipos:
    - Baixa Fidelidade (Wireframes):
      - Geral:
        - Página Inicial: prototipos/baixa fidelidade (wireframe)/01_pagina_inicial.png
        - Detalhes do Evento: prototipos/baixa fidelidade (wireframe)/02_detalhes_evento.png
      - Autenticação:
        - Login: prototipos/baixa fidelidade (wireframe)/03_autenticacao_login.png
        - Cadastro: prototipos/baixa fidelidade (wireframe)/04_autenticacao_cadastro.png
        - Esqueci a Senha: prototipos/baixa fidelidade (wireframe)/05_autenticacao_esqueci_senha.png
      - Aluno:
        - Perfil: prototipos/baixa fidelidade (wireframe)/06_aluno_perfil.png
        - Eventos Inscritos: prototipos/baixa fidelidade (wireframe)/07_aluno_eventos_inscritos.png
        - Editar Dados: prototipos/baixa fidelidade (wireframe)/08_aluno_editar_dados.png
      - Organizador (Org):
        - Perfil: prototipos/baixa fidelidade (wireframe)/09_org_perfil.png
        - Editar Dados: prototipos/baixa fidelidade (wireframe)/10_org_editar_dados.png
        - Eventos Criados: prototipos/baixa fidelidade (wireframe)/11_org_eventos_criados.png
        - Detalhe do Evento: prototipos/baixa fidelidade (wireframe)/12_org_evento_detalhe.png
        - Novo / Editar Evento: prototipos/baixa fidelidade (wireframe)/13_org_evento_novo_editar.png
        - Reservas de Espaço: prototipos/baixa fidelidade (wireframe)/14_org_reservas_espaco.png
        - Nova Reserva: prototipos/baixa fidelidade (wireframe)/15_org_reserva_nova.png
        - Gerenciar Inscritos: prototipos/baixa fidelidade (wireframe)/16_org_gerenciar_inscritos.png
        - Organizações Vinculadas: prototipos/baixa fidelidade (wireframe)/17_org_organizacoes_vinculadas.png
        - Editar Organização: prototipos/baixa fidelidade (wireframe)/18_org_organizacao_editar.png
      - Gestor:
        - Perfil: prototipos/baixa fidelidade (wireframe)/19_gestor_perfil.png
        - Editar Dados: prototipos/baixa fidelidade (wireframe)/20_gestor_editar_dados.png
        - Espaços Esportivos: prototipos/baixa fidelidade (wireframe)/21_gestor_espacos_esportivos.png
        - Novo / Editar Espaço: prototipos/baixa fidelidade (wireframe)/22_gestor_espaco_novo_editar.png
        - Reservas: prototipos/baixa fidelidade (wireframe)/23_gestor_reservas.png
        - Usuários Admin: prototipos/baixa fidelidade (wireframe)/24_gestor_usuarios_admin.png

theme:
  name: material