@startuml
!define DARKBLUE #102e4a
!define GREEN #1b7a43
!define WHITE #FFFFFF

skinparam sequence {
    ArrowColor GREEN
    ActorBorderColor GREEN
    LifeLineBorderColor DARKBLUE
    LifeLineBackgroundColor GREEN
    
    ParticipantBorderColor GREEN
    ParticipantBackgroundColor DARKBLUE
    ParticipantFontColor WHITE
    
    ActorBackgroundColor DARKBLUE
    ActorFontColor DARKBLUE
}

skinparam note {
    BackgroundColor GREEN
    BorderColor DARKBLUE
    FontColor WHITE
}

autonumber

actor "Aluno" as aluno
box "SIGEsporte" #F0F8FF
    participant "Interface (View)" as view
    participant "Evento" as evento
    participant "Inscricao" as inscricao
end box
actor "Organizador" as org

== FASE 1: Consulta de Eventos (Aluno) ==

aluno -> view : Acessa portal de eventos
activate view

view -> evento : objects.filter(data_realizacao__gte=hoje)
activate evento
evento --> view : QuerySet[Eventos Futuros]
deactivate evento

view --> aluno : Exibe catálogo de eventos disponíveis

aluno -> view : Clica em "Ver Detalhes" de um evento
view -> evento : objects.get(id=evento_id)
activate evento
evento --> view : Instância do Evento
deactivate evento

view --> aluno : Exibe página com detalhes do evento
deactivate view

== FASE 2: Inclusão da Inscrição (Aluno) ==

aluno -> view : Clica em "Inscrição"
activate view

view -> inscricao : objects.filter(participante=aluno, evento=evento_id).exists()
activate inscricao
inscricao --> view : Retorna Booleano
deactivate inscricao

alt Aluno já possui inscrição
    view --> aluno : Exibe aviso ("Você já está inscrito neste evento")
else Nova inscrição
    view -> inscricao : create(participante=aluno, evento=evento_id, status='P')
    activate inscricao
    inscricao --> view : inscricao_id
    deactivate inscricao
    
    view --> aluno : Mensagem de Sucesso ("Inscrição solicitada. Aguardando aprovação")
end
deactivate view

== FASE 3: Avaliação e Aprovação (Organizador) ==

org -> view : Acessa painel de gestão do evento
activate view

view -> inscricao : objects.filter(evento=evento_id, status='P')
activate inscricao
inscricao --> view : QuerySet[Inscrições Pendentes]
deactivate inscricao

view --> org : Exibe lista de alunos aguardando aprovação

org -> view : Clica em "Aprovar" na linha do aluno
view -> inscricao : aprovar(organizador=org)
activate inscricao

note right of inscricao
    Altera o status para 'A' (Aprovada)
    e salva no banco de dados.
end note

inscricao --> view : Inscrição atualizada
deactivate inscricao

view --> org : Mensagem de Sucesso ("Inscrição do aluno aprovada")
deactivate view

@enduml