# Generated by Django 6.0.5 on 2026-05-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(verbose_name='Horário do Evento'),
        ),
    ]
