# Generated by Django 6.0.5 on 2026-06-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dados_iniciais'),
        ('core', '0005_organizacao'),
    ]

    operations = [
    ]
