# Generated by Django 6.0.5 on 2026-06-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0002_dados_iniciais_0005_organizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(verbose_name='Horario do Evento'),
        ),
    ]
