# Generated by Django 6.0.5 on 2026-06-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vagas_ocupadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Vagas Ocupadas'),
        ),
    ]
