# Generated by Django 6.0.5 on 2026-06-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evento_vagas_ocupadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEspaco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora de Término')),
                ('motivo_reprovacao', models.TextField(blank=True, null=True, verbose_name='Motivo da Reprovação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_avaliadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.espacofisico', verbose_name='Espaço Físico')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.evento', verbose_name='Evento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Reserva de Espaço',
                'verbose_name_plural': 'Reservas de Espaço',
                'ordering': ['-criado_em'],
            },
        ),
    ]
