# Generated by Django 6.0.5 on 2026-06-14 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inscricao_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioorganizacao',
            options={'verbose_name': 'Membro de Organizacao', 'verbose_name_plural': 'Membros de Organizacoes'},
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='descricao',
            field=models.TextField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='organizacoes/', verbose_name='Foto da Organizacao'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome da Organizacao'),
        ),
        migrations.AlterField(
            model_name='usuarioorganizacao',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.organizacao', verbose_name='Organizacao'),
        ),
        migrations.AlterField(
            model_name='usuarioorganizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacoes_vinculadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
