# Generated by Django 6.0.5 on 2026-06-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_usuarioorganizacao_options_and_more'),
        ('core', '0013_evento_vinculo_organizador_organizacao'),
    ]

    operations = [
    ]
